
window.onload=function(){
var head=document.getElementById('h')
head.style.color="white"
head.style.backgroundColor="black"
head.style.transform="uppercase";
var ved= document.getElementById("para");
ved.innerHTML="chainsmoker"
var ved2= document.getElementById("para2");
ved2.innerHTML="commando3"
var f=document.getElementById('vi')
f.src="Photo Reprise Version (Hindi_Punjabi) x Zara Tasveer Se Tu _ Luka Chuppi _ Acoustic Singh - YouTube (720p).mp4"

var u=document.getElementById('vi2')
u.src = "commando3.mp4"
var u=document.getElementById('vi3')
u.src = "Dhvani Bhanushali Live _ IIFA Rocks Performance 2019 - YouTube (720p).mp4"
var u=document.getElementById('vi4')
u.src = "Travel Medley 2018 _ Twin Strings Ft. Manav, Pavitra - YouTube (720p).mp4"
var u=document.getElementById('vi5')
u.src = "Aaj Bhi (Official Video) - Vishal Mishra _ Ali Fazal, Surbhi Jyoti _ VYRLOriginals - YouTube (720p).mp4"
var u=document.getElementById('vi6')
u.src = "Arijit Singh with his soulful performance _ 6th Royal Stag Mirchi Music Awards _ Radio Mirchi - YouTube (360p).mp4"
var u=document.getElementById('vi7')
u.src = "Arijit Singh _ Yaariyan _ Full Song _ Rajma Chawal Movie _ 2018 - YouTube (360p).mp4"
var u=document.getElementById('vi8')
u.src = "Dilbara - Full Song _ Dhoom _ Abhishek Bachchan _ Uday Chopra _ Esha Deol _ Abhijeet _ Sowmya - YouTube (720p).mp4"
var u=document.getElementById('vi9')
u.src = "Crazy Kiya Re - Full Song _ Dhoom_2 _ Hrithik Roshan _ Aishwarya Rai _ Sunidhi Chauhan - YouTube (720p).mp4"
var u=document.getElementById('vi10')
u.src = "Bandeya Rey Bandeya Lyrical _ SIMMBA _ Ranveer Singh, Sara Ali Khan _ Arijit Singh _ Asees Kaur - YouTube (720p).mp4"
var u=document.getElementById('vi11')
u.src = "LYRICAL_ Saugandh Mujhe Iss Mitti Ki Song _ PM Narendra Modi _ Vivek Oberoi_Sukhwinder Singh,Shashi - YouTube (720p).mp4"
var o=document.getElementById('vi12')
o.src = "s.mp4"
var u=document.getElementById('vi13')
u.src = "DOORIYAN.mp4"
var u=document.getElementById('vi14')
u.src = "1.mp4"
var u=document.getElementById('vi15')
u.src = "2.mp4"
var u=document.getElementById('vi16')
u.src = "3.mp4"
var u=document.getElementById('vi18')
u.src = "4.mp4"
var u=document.getElementById('vi19')
u.src = "5.mp4"
var u=document.getElementById('vi20')
u.src = "6.mp4"
var u=document.getElementById('vi21')
u.src = "8.mp4"
var u=document.getElementById('vi22')
u.src = "7.mp4"
var u=document.getElementById('vi24')
u.src = "9.mp4"
var u=document.getElementById('vi25')
u.src = "10.mp4"
var u=document.getElementById('vi26')
u.src = "11.mp4"
var u=document.getElementById('vi27')
u.src = "12.mp4"
var u=document.getElementById('vi28')
u.src = "13.mp4"
var u=document.getElementById('vi29')
u.src = "14.mp4"
var u=document.getElementById('vi30')
u.src = "15.mp4"
var u=document.getElementById('vi31')
u.src = "16.mp4"
var u=document.getElementById('vi32')
u.src = "17.mp4"
var u=document.getElementById('vi33')
u.src = "18.mp4"
var u=document.getElementById('vi34')
u.src = "19.mp4"
var u=document.getElementById('vi35')
u.src = "20.mp4"
var e = document.getElementsByTagName('a');
e[0].href="Photo Reprise Version (Hindi_Punjabi) x Zara Tasveer Se Tu _ Luka Chuppi _ Acoustic Singh - YouTube (720p).mp4";
e[2].href="Dhvani Bhanushali Live _ IIFA Rocks Performance 2019 - YouTube (720p).mp4";
e[1].href="commando3.mp4";
e[3].href="Travel Medley 2018 _ Twin Strings Ft. Manav, Pavitra - YouTube (720p).mp4"
e[4].href="Aaj Bhi (Official Video) - Vishal Mishra _ Ali Fazal, Surbhi Jyoti _ VYRLOriginals - YouTube (720p).mp4"
e[5].href="Arijit Singh with his soulful performance _ 6th Royal Stag Mirchi Music Awards _ Radio Mirchi - YouTube (360p).mp4"
e[8].href="Crazy Kiya Re - Full Song _ Dhoom_2 _ Hrithik Roshan _ Aishwarya Rai _ Sunidhi Chauhan - YouTube (720p).mp4"
e[6].href="Arijit Singh _ Yaariyan _ Full Song _ Rajma Chawal Movie _ 2018 - YouTube (360p).mp4"
e[7].href="Dilbara - Full Song _ Dhoom _ Abhishek Bachchan _ Uday Chopra _ Esha Deol _ Abhijeet _ Sowmya - YouTube (720p).mp4"
e[9].href="Bandeya Rey Bandeya Lyrical _ SIMMBA _ Ranveer Singh, Sara Ali Khan _ Arijit Singh _ Asees Kaur - YouTube (720p).mp4"
e[10].href="LYRICAL_ Saugandh Mujhe Iss Mitti Ki Song _ PM Narendra Modi _ Vivek Oberoi_Sukhwinder Singh,Shashi - YouTube (720p).mp4"
e[11].href="s.mp4"
e[12].href="DOORIYAN.mp4"
var w = document.getElementsByTagName('a');
w[13].href="1.mp4"
w[14].href="2.mp4"
w[15].href="3.mp4"
w[16].href="4.mp4"
w[17].href="5.mp4"
w[18].href="6.mp4"
w[19].href="8.mp4"
w[20].href="7.mp4"
w[22].href="9.mp4"//element skiped
w[23].href="10.mp4"//element skiped
w[24].href="11.mp4"//element skiped
w[25].href="12.mp4"//element skiped
w[26].href="13.mp4"
w[27].href="14.mp4"
w[28].href="15.mp4"
w[29].href="16.mp4"
w[30].href="17.mp4"
w[31].href="18.mp4"
w[32].href="19.mp4"
w[33].href="20.mp4"
}
